/* A2.2.B Import saledata2.txt */

%web_drop_table(MYSASLIB.SALE2);

FILENAME REFFILE '/home/gsturrock0/UNIT2/saledata2.txt';

PROC IMPORT DATAFILE=REFFILE
	DBMS=DLM
	OUT=MYSASLIB.SALE2 (RENAME=(VAR1=ID VAR2=SALETYPE VAR3=QUANTITY VAR4=AMOUNT));
	GETNAMES=NO;
	DATAROW=1;
RUN;

*PROC CONTENTS DATA=MYSASLIB.SALE2; RUN;

%web_open_table(MYSASLIB.SALE2);