DATA SOMEMISS2; SET MYSASLIB.SOMEMISS;
GENDER=UPCASE(GENDER);
IF GENDER='MAIL' THEN GENDER='MALE';
AGEN=INPUT(AGE,3.);
IF AGEN > 120 THEN AGEN='.';
RUN;

PROC FREQ DATA=SOMEMISS2;
  TABLES GENDER AGEN;
RUN;