DATA NEW; SET MYSASLIB.WOUND;

SELECT; 
  WHEN (AGE <= 4) AGEGP='TODDLER';
  WHEN (AGE > 4 AND AGE <= 12) AGEGP="CHILD"; 
  WHEN (AGE > 12 AND AGE <= 18) AGEGP="TEEN"; 
  WHEN (AGE > 18) AGEGP = "ADULT";
  OTHERWISE AGEGP='';
END;
RUN ;

*PROC MEANS DATA=NEW;
*RUN;
PROC PRINT DATA=NEW;
RUN;

TITLE;FOOTNOTE;

